-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 18:47:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema loanapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loanapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loanapp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `loanapp` ;

-- -----------------------------------------------------
-- Table `loanapp`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loanapp`.`admin` (
  `admin_id` VARCHAR(255) NOT NULL,
  `a_email` VARCHAR(255) NOT NULL,
  `a_password` VARCHAR(255) NOT NULL,
  `fname` VARCHAR(255) NOT NULL,
  `lname` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loanapp`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loanapp`.`customers` (
  `customer_id` VARCHAR(255) NOT NULL,
  `accno` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `role` VARCHAR(255) NULL DEFAULT 'customer',
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loanapp`.`loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loanapp`.`loans` (
  `loan_id` VARCHAR(255) NOT NULL,
  `emi` BIGINT NULL DEFAULT NULL,
  `interest_rate` INT NULL DEFAULT NULL,
  `loan_amount` BIGINT NOT NULL,
  `loan_reason` VARCHAR(255) NULL DEFAULT NULL,
  `loan_tenure` INT NULL DEFAULT NULL,
  `loan_terms` INT NULL DEFAULT NULL,
  `loan_type` VARCHAR(255) NULL DEFAULT NULL,
  `maturity_date` VARCHAR(255) NULL DEFAULT NULL,
  `payment_cycles` INT NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `trade_date` DATE NULL DEFAULT NULL,
  `fk_customer_id` VARCHAR(255) NULL DEFAULT NULL,
  `loan_status` VARCHAR(255) NULL DEFAULT NULL,
  `total_amount` BIGINT NULL DEFAULT NULL,
  `paid_amount` BIGINT NULL DEFAULT '0',
  PRIMARY KEY (`loan_id`),
  INDEX `FKbxym66460gcbuvpkucrln0mw8` (`fk_customer_id` ASC) VISIBLE,
  CONSTRAINT `FKbxym66460gcbuvpkucrln0mw8`
    FOREIGN KEY (`fk_customer_id`)
    REFERENCES `loanapp`.`customers` (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `loanapp`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loanapp`.`payments` (
  `payment_id` VARCHAR(255) NOT NULL,
  `due_date` DATE NULL DEFAULT NULL,
  `payment_date` DATE NULL DEFAULT NULL,
  `payment_status` VARCHAR(255) NULL DEFAULT NULL,
  `fk_loan_id` VARCHAR(255) NULL DEFAULT NULL,
  `paid_amount` BIGINT NULL DEFAULT '0',
  `remain_cycles` INT NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `FKaorrpdnqb6ejm4nlpllq05r44` (`fk_loan_id` ASC) VISIBLE,
  CONSTRAINT `FKaorrpdnqb6ejm4nlpllq05r44`
    FOREIGN KEY (`fk_loan_id`)
    REFERENCES `loanapp`.`loans` (`loan_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
